const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Plugins.NinePatch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnAnyItemSet,
		C3.Plugins.LocalStorage.Exps.Key,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Plugins.LocalStorage.Cnds.OnAllSetsComplete,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnAllGetsComplete,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Text.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Logo: 0},
	{TombolMulai: 0},
	{LoadingContainer: 0},
	{Touch: 0},
	{Tween: 0},
	{TiledBackground2: 0},
	{bg2: 0},
	{Mentor: 0},
	{TombolLanjut: 0},
	{Audio: 0},
	{TombolSkip: 0},
	{DialogBertemuMentor: 0},
	{TextContainer: 0},
	{KartuAvatar: 0},
	{Judul3: 0},
	{bg3: 0},
	{BingkaiPilih: 0},
	{InputNama: 0},
	{InputTextContainer: 0},
	{TombolKonfirmasi: 0},
	{TiledBackground: 0},
	{Text2: 0},
	{TombolYa: 0},
	{TombolTidak: 0},
	{kosong: 0},
	{Pemain: 0},
	{BgBertemuMentor: 0},
	{Mentor2: 0},
	{BtnSiap: 0},
	{BtnTunggu: 0},
	{PopUpTungguContainer: 0},
	{DialogTunggu: 0},
	{BtnMengerti: 0},
	{BgKonsepKeliling: 0},
	{PendahuluanKonsepKeliling: 0},
	{PendahuluanKonsepKeliling2: 0},
	{MentorKonsepKeliling: 0},
	{BubleText2: 0},
	{ID: 0},
	{Sine: 0},
	{Marker: 0},
	{bg_gradient: 0},
	{txt_title: 0},
	{txt_soal: 0},
	{instruction_box: 0},
	{garis_ukuran: 0},
	{Text_Ukuran: 0},
	{input_jawaban: 0},
	{btn_cek: 0},
	{sebelum_jawaban: 0},
	{setelah_jawaban: 0},
	{txt_feedback: 0},
	{Particles: 0},
	{bg_pagar: 0},
	{Fade: 0},
	{spr_salah: 0},
	{Bg_Room: 0},
	{IsClone: 0},
	{HomeX: 0},
	{HomeY: 0},
	{DragDrop: 0},
	{Spr_Ubin: 0},
	{IsFilled: 0},
	{Spr_Slot: 0},
	{Txt_Counter: 0},
	{Btn_Reset: 0},
	{Buble_Instruksi: 0},
	{btn_paham: 0},
	{bg_tantangan_konsep_luas: 0},
	{txt_soal_tantangan_luas: 0},
	{txt_sebelum_input_konsep_luas: 0},
	{input_jawaban_Konsep: 0},
	{Spr_BlueprintGrid: 0},
	{Spr_UbinGrid: 0},
	{furniture: 0},
	{Spr_Mentor_Excited: 0},
	{Spr_Avatar_Happy: 0},
	{Spr_BadgeSelesai: 0},
	{Particles_Confetti: 0},
	{bg_2_5: 0},
	{Spr_SpeechBubble: 0},
	{Txt_MentorSpeech: 0},
	{btn_KeKantor: 0},
	{Spr_BG_Kantor: 0},
	{Spr_MejaProyek: 0},
	{Spr_LemariArsip: 0},
	{Spr_PapanTulis: 0},
	{Spr_Pintu: 0},
	{Spr_UI_Frame: 0},
	{Spr_Frame_Isi: 0},
	{txt_Frame_Nama: 0},
	{Spr_Dimmer: 0},
	{Spr_DeskBG: 0},
	{ProyekID: 0},
	{Btn_Proyek: 0},
	{Spr_Gembok: 0},
	{Btn_Close: 0},
	{Txt_Label_Tombol: 0},
	{Sprite: 0},
	{MateriID: 0},
	{LevelID: 0},
	{Spr_PosSatpam: 0},
	{Spr_TamanSegitiga: 0},
	{spr_lapangan: 0},
	{spr_kolamHexa: 0},
	{spr_KolamPanjang: 0},
	{spr_KantorArsitek: 0},
	{Spr_RumahHijau: 0},
	{Spr_RumahOrange: 0},
	{Spr_RumahMerah: 0},
	{Spr_RumahKuning: 0},
	{Spr_RumahBiru: 0},
	{Spr_RumahPink: 0},
	{Spr_Plaza: 0},
	{Spr_RumahUngu: 0},
	{Bg_Dialog: 0},
	{Txt_Judul: 0},
	{Btn_Mulai: 0},
	{LocalStorage: 0},
	{Spr_CloseUpPapanTulis: 0},
	{Spr_Sticky_KPersegi: 0},
	{Spr_Sticky_KPPanjang: 0},
	{Spr_Sticky_KSegitiga: 0},
	{Spr_Sticky_KSBanyak: 0},
	{Spr_Sticky_KGabung: 0},
	{Spr_Sticky_LPesergi: 0},
	{Spr_Sticky_LPPanjang: 0},
	{Spr_Sticky_LSegitiga: 0},
	{Spr_Sticky_LGabung: 0},
	{Spr_Sticky_HubKL: 0},
	{bg_Kantor: 0},
	{txt_4xs: 0},
	{spr_klien: 0},
	{txt_Dialog: 0},
	{txt_Pertanyaan: 0},
	{bg_Layout12: 0},
	{Spr_buble_text: 0},
	{spr_klien2: 0},
	{AvatarID: 0},
	{spr_avatar12: 0},
	{txt_Klien_12: 0},
	{txt_avatar_12: 0},
	{txt_tap_lanjut: 0},
	{Spr_TapArea: 0},
	{txt_mentor: 0},
	{txt_ukuran_atas: 0},
	{txt_ukuran_kiri: 0},
	{txt_ukuran_bawah: 0},
	{txt_ukuran_kanan: 0},
	{Spr_highlight_atas: 0},
	{Spr_highlight_bawah: 0},
	{Spr_highlight_kiri: 0},
	{Spr_highlight_kanan: 0},
	{btn_pilihan1: 0},
	{btn_pilihan2: 0},
	{input_p: 0},
	{input_l: 0},
	{input_2p: 0},
	{input_2l: 0},
	{input_hasil: 0},
	{btn_cek_step1: 0},
	{btn_cek_step2: 0},
	{btn_cek_step3: 0},
	{Txt_pilih_rumus: 0},
	{Browser: 0},
	{Txt_step1_rumus1: 0},
	{Txt_step2_rumus1: 0},
	{spr_frame_text: 0},
	{Txt_step3_rumus1: 0},
	{Txt_hasil_akhir: 0},
	{bg_Taman: 0},
	{spr_BuSari: 0},
	{spr_avatar13: 0},
	{spr_Mentor13: 0},
	{txt_UkuranSisi1: 0},
	{txt_UkuranSisi2: 0},
	{txt_UkuranSisi3: 0},
	{txt_Dialog_BuSari: 0},
	{txt_Dialog_Avatar: 0},
	{txt_Dialog_Mentor: 0},
	{txt_Pertanyaan13: 0},
	{input_jawaban13: 0},
	{btn_KeKantor13: 0},
	{txt_narasi: 0},
	{Family_Node: 0},
	{Family_Sticky: 0},
	{Family_input: 0},
	{AvatarPilihan: 0},
	{NamaUser: 0},
	{TargetSekarang: 0},
	{PosisiLamaX: 0},
	{PosisiLamaY: 0},
	{ScoreKonsepLuas: 0},
	{Skor_P1: 0},
	{Skor_P2: 0},
	{DataLoaded: 0},
	{Global_SelectedProject: 0},
	{Var_CurrentProgress: 0},
	{Temp_TargetLayout: 0},
	{MateriStep: 0},
	{DialogStep: 0},
	{CanTap: 0},
	{PilihanRumus: 0},
	{MateriPhase: 0},
	{Layout13_Step: 0},
	{Layout13_CanTap: 0},
	{Layout13_AnswerCorrect: 0},
	{jawaban: 0},
	{Layout13_InGameplay: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	TombolMulai: class extends self.ISpriteInstance {},
	LoadingContainer: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	bg2: class extends self.ISpriteInstance {},
	Mentor: class extends self.ISpriteInstance {},
	TombolLanjut: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	TombolSkip: class extends self.ISpriteInstance {},
	DialogBertemuMentor: class extends self.ITextInstance {},
	TextContainer: class extends self.ISpriteInstance {},
	KartuAvatar: class extends self.ISpriteInstance {},
	Judul3: class extends self.ITextInstance {},
	bg3: class extends self.ISpriteInstance {},
	BingkaiPilih: class extends self.ISpriteInstance {},
	InputNama: class extends self.ITextInputInstance {},
	InputTextContainer: class extends self.ISpriteInstance {},
	TombolKonfirmasi: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Text2: class extends self.ITextInstance {},
	TombolYa: class extends self.ISpriteInstance {},
	TombolTidak: class extends self.ISpriteInstance {},
	kosong: class extends self.ITextInstance {},
	Pemain: class extends self.ISpriteInstance {},
	BgBertemuMentor: class extends self.ISpriteInstance {},
	Mentor2: class extends self.ISpriteInstance {},
	BtnSiap: class extends self.ISpriteInstance {},
	BtnTunggu: class extends self.ISpriteInstance {},
	PopUpTungguContainer: class extends self.ISpriteInstance {},
	DialogTunggu: class extends self.ITextInstance {},
	BtnMengerti: class extends self.ISpriteInstance {},
	BgKonsepKeliling: class extends self.ISpriteInstance {},
	PendahuluanKonsepKeliling: class extends self.ITextInstance {},
	PendahuluanKonsepKeliling2: class extends self.ITextInstance {},
	MentorKonsepKeliling: class extends self.ISpriteInstance {},
	BubleText2: class extends self.ISpriteInstance {},
	Marker: class extends self.ISpriteInstance {},
	bg_gradient: class extends self.ISpriteInstance {},
	txt_title: class extends self.ITextInstance {},
	txt_soal: class extends self.ITextInstance {},
	instruction_box: class extends self.ISpriteInstance {},
	garis_ukuran: class extends self.ISpriteInstance {},
	Text_Ukuran: class extends self.ITextInstance {},
	input_jawaban: class extends self.ITextInputInstance {},
	btn_cek: class extends self.ISpriteInstance {},
	sebelum_jawaban: class extends self.ITextInstance {},
	setelah_jawaban: class extends self.ITextInstance {},
	txt_feedback: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	bg_pagar: class extends self.ISpriteInstance {},
	spr_salah: class extends self.ISpriteInstance {},
	Bg_Room: class extends self.ISpriteInstance {},
	Spr_Ubin: class extends self.ISpriteInstance {},
	Spr_Slot: class extends self.ISpriteInstance {},
	Txt_Counter: class extends self.ITextInstance {},
	Btn_Reset: class extends self.ISpriteInstance {},
	Buble_Instruksi: class extends self.ISpriteInstance {},
	btn_paham: class extends self.ISpriteInstance {},
	bg_tantangan_konsep_luas: class extends self.ISpriteInstance {},
	txt_soal_tantangan_luas: class extends self.ITextInstance {},
	txt_sebelum_input_konsep_luas: class extends self.ITextInstance {},
	input_jawaban_Konsep: class extends self.ITextInputInstance {},
	Spr_BlueprintGrid: class extends self.ISpriteInstance {},
	Spr_UbinGrid: class extends self.ISpriteInstance {},
	furniture: class extends self.ISpriteInstance {},
	Spr_Mentor_Excited: class extends self.ISpriteInstance {},
	Spr_Avatar_Happy: class extends self.ISpriteInstance {},
	Spr_BadgeSelesai: class extends self.ISpriteInstance {},
	Particles_Confetti: class extends self.IParticlesInstance {},
	bg_2_5: class extends self.ISpriteInstance {},
	Spr_SpeechBubble: class extends self.ISpriteInstance {},
	Txt_MentorSpeech: class extends self.ITextInstance {},
	btn_KeKantor: class extends self.ISpriteInstance {},
	Spr_BG_Kantor: class extends self.ISpriteInstance {},
	Spr_MejaProyek: class extends self.ISpriteInstance {},
	Spr_LemariArsip: class extends self.ISpriteInstance {},
	Spr_PapanTulis: class extends self.ISpriteInstance {},
	Spr_Pintu: class extends self.ISpriteInstance {},
	Spr_UI_Frame: class extends self.ISpriteInstance {},
	Spr_Frame_Isi: class extends self.ISpriteInstance {},
	txt_Frame_Nama: class extends self.ITextInstance {},
	Spr_Dimmer: class extends self.ISpriteInstance {},
	Spr_DeskBG: class extends self.ISpriteInstance {},
	Btn_Proyek: class extends self.ISpriteInstance {},
	Spr_Gembok: class extends self.ISpriteInstance {},
	Btn_Close: class extends self.ISpriteInstance {},
	Txt_Label_Tombol: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Spr_PosSatpam: class extends self.ISpriteInstance {},
	Spr_TamanSegitiga: class extends self.ISpriteInstance {},
	spr_lapangan: class extends self.ISpriteInstance {},
	spr_kolamHexa: class extends self.ISpriteInstance {},
	spr_KolamPanjang: class extends self.ISpriteInstance {},
	spr_KantorArsitek: class extends self.ISpriteInstance {},
	Spr_RumahHijau: class extends self.ISpriteInstance {},
	Spr_RumahOrange: class extends self.ISpriteInstance {},
	Spr_RumahMerah: class extends self.ISpriteInstance {},
	Spr_RumahKuning: class extends self.ISpriteInstance {},
	Spr_RumahBiru: class extends self.ISpriteInstance {},
	Spr_RumahPink: class extends self.ISpriteInstance {},
	Spr_Plaza: class extends self.ISpriteInstance {},
	Spr_RumahUngu: class extends self.ISpriteInstance {},
	Bg_Dialog: class extends self.I9PatchInstance {},
	Txt_Judul: class extends self.ITextInstance {},
	Btn_Mulai: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Spr_CloseUpPapanTulis: class extends self.ISpriteInstance {},
	Spr_Sticky_KPersegi: class extends self.ISpriteInstance {},
	Spr_Sticky_KPPanjang: class extends self.ISpriteInstance {},
	Spr_Sticky_KSegitiga: class extends self.ISpriteInstance {},
	Spr_Sticky_KSBanyak: class extends self.ISpriteInstance {},
	Spr_Sticky_KGabung: class extends self.ISpriteInstance {},
	Spr_Sticky_LPesergi: class extends self.ISpriteInstance {},
	Spr_Sticky_LPPanjang: class extends self.ISpriteInstance {},
	Spr_Sticky_LSegitiga: class extends self.ISpriteInstance {},
	Spr_Sticky_LGabung: class extends self.ISpriteInstance {},
	Spr_Sticky_HubKL: class extends self.ISpriteInstance {},
	bg_Kantor: class extends self.ISpriteInstance {},
	txt_4xs: class extends self.ITextInstance {},
	spr_klien: class extends self.ISpriteInstance {},
	txt_Dialog: class extends self.ITextInstance {},
	txt_Pertanyaan: class extends self.ITextInstance {},
	bg_Layout12: class extends self.ISpriteInstance {},
	Spr_buble_text: class extends self.ISpriteInstance {},
	spr_klien2: class extends self.ISpriteInstance {},
	spr_avatar12: class extends self.ISpriteInstance {},
	txt_Klien_12: class extends self.ITextInstance {},
	txt_avatar_12: class extends self.ITextInstance {},
	txt_tap_lanjut: class extends self.ITextInstance {},
	Spr_TapArea: class extends self.ISpriteInstance {},
	txt_mentor: class extends self.ITextInstance {},
	txt_ukuran_atas: class extends self.ITextInstance {},
	txt_ukuran_kiri: class extends self.ITextInstance {},
	txt_ukuran_bawah: class extends self.ITextInstance {},
	txt_ukuran_kanan: class extends self.ITextInstance {},
	Spr_highlight_atas: class extends self.ISpriteInstance {},
	Spr_highlight_bawah: class extends self.ISpriteInstance {},
	Spr_highlight_kiri: class extends self.ISpriteInstance {},
	Spr_highlight_kanan: class extends self.ISpriteInstance {},
	btn_pilihan1: class extends self.ISpriteInstance {},
	btn_pilihan2: class extends self.ISpriteInstance {},
	input_p: class extends self.ITextInputInstance {},
	input_l: class extends self.ITextInputInstance {},
	input_2p: class extends self.ITextInputInstance {},
	input_2l: class extends self.ITextInputInstance {},
	input_hasil: class extends self.ITextInputInstance {},
	btn_cek_step1: class extends self.ISpriteInstance {},
	btn_cek_step2: class extends self.ISpriteInstance {},
	btn_cek_step3: class extends self.ISpriteInstance {},
	Txt_pilih_rumus: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Txt_step1_rumus1: class extends self.ITextInstance {},
	Txt_step2_rumus1: class extends self.ITextInstance {},
	spr_frame_text: class extends self.ISpriteInstance {},
	Txt_step3_rumus1: class extends self.ITextInstance {},
	Txt_hasil_akhir: class extends self.ITextInstance {},
	bg_Taman: class extends self.ISpriteInstance {},
	spr_BuSari: class extends self.ISpriteInstance {},
	spr_avatar13: class extends self.ISpriteInstance {},
	spr_Mentor13: class extends self.ISpriteInstance {},
	txt_UkuranSisi1: class extends self.ITextInstance {},
	txt_UkuranSisi2: class extends self.ITextInstance {},
	txt_UkuranSisi3: class extends self.ITextInstance {},
	txt_Dialog_BuSari: class extends self.ITextInstance {},
	txt_Dialog_Avatar: class extends self.ITextInstance {},
	txt_Dialog_Mentor: class extends self.ITextInstance {},
	txt_Pertanyaan13: class extends self.ITextInstance {},
	input_jawaban13: class extends self.ITextInputInstance {},
	btn_KeKantor13: class extends self.ISpriteInstance {},
	txt_narasi: class extends self.ITextInstance {},
	Family_Node: class extends self.ISpriteInstance {},
	Family_Sticky: class extends self.ISpriteInstance {},
	Family_input: class extends self.ITextInputInstance {}
}